#!/usr/bin/python3

if __name__ == "__main__":
    import sys
    prime_func = __import__('prime_func').prime_factor
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        quit()
    with open(sys.argv[1], encoding = 'utf-8') as f:
        for line in f:
            line = int(line)
            val = prime_func(line)
            print(f"{line}={int(val[0])}*{val[1]}")
